### ISSUE TITLE
Bloodhound not showing information

### ISSUE THREAD

**Issue by cmlaird** [flighttactics/TAKAware#48] opened 2024-12-04 02:56 UTC
**Describe the bug**
When selecting Bloodhound between 2 markers, no information is shown on the map.

**Expected behavior**
Looking for bearing, speed, and ETA like shown on R&B line in ATAK or in some other way![image](https://github.com/user-attachments/assets/45cf1b12-db9e-48ae-b765-126610060efc)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 16 Pro Max
 - OS: iOS 18.2 beta 
 - Version: latest
 - App Store or TestFlight?: TF

**Additional context**

**Comment by CoryFoy** [comment] 2024-12-04 20:45
Duplicate of #19

**Closed as completed by CoryFoy** 2024-12-04 20:45 UTC
Labels: duplicate
