### ISSUE TITLE
Labels on markers

### ISSUE THREAD

**Issue by cmlaird** [flighttactics/TAKAware#49] opened 2024-12-04 02:58 UTC
**Is your feature request related to a problem? Please describe.**
Only way to see marker label is to click. 

**Describe the solution you'd like**
Looking for same implementation as ATAK where marker title shows up at zoom level determined my marker or plugin 

**Additional context**

**Comment by CoryFoy** [comment] 2024-12-04 20:41
Duplicate of #3

**Closed as completed by CoryFoy** 2024-12-04 20:41 UTC
Labels: duplicate
